#!/bin/bash


set -e


SCRIPT_DIR=$(readlink -m $(dirname $0))
PROBLEMS_DIR=$SCRIPT_DIR/problems
TARGZ_PATH=$SCRIPT_DIR/final.tar.gz


cd $SCRIPT_DIR


TEMP_DIR=$(mktemp -d)
trap cleanup exit

function cleanup()
{
    if [ -e $TEMP_DIR ]; then
        rm -rf $TEMP_DIR
    fi
}

function require_file()
{
    if [ ! -f $1 ]; then
        echo "* No file named '$(basename $1)' found in the problems/ directory."
        echo "  (Did you complete this problem?)"
        echo "  (Did you name the file precisely as '$(basename $1)', including spelling"
        echo "   and capitalization?)"
    fi
}

function require_pdf()
{
    if [ ! -f $1 ]; then
        echo "* No file named '$(basename $1)' found in the problems/ directory."
        echo "  (Did you complete this problem?)"
        echo "  (Did you name the file precisely as '$(basename $1)', including spelling"
        echo "   and capitalization?)"
    else
        set +e

        pdfinfo $1 >/dev/null 2>&1

        PDF_CHECK_RESULT=$?
        
        if [ $PDF_CHECK_RESULT -ne 0 ]; then
            echo "* The file named '$(basename $1)' is likely not in the PDF format,"
            echo "  as required.  See the project write-up for instructions on"
            echo "  creating PDFs and be sure you've followed them."
        fi

        set -e
    fi
}

function gather_file()
{
    if [ -f $1 ]; then
        cp $1 $TEMP_DIR
    fi
}


# Check that the necessary files are there and in the right format.
echo "Checking your problems/ directory for the appropriate files..."
require_pdf $PROBLEMS_DIR/problem1.pdf
require_pdf $PROBLEMS_DIR/problem2.pdf
require_file $PROBLEMS_DIR/problem3.hpp
require_file $PROBLEMS_DIR/problem3.cpp
require_pdf $PROBLEMS_DIR/problem4.pdf
require_pdf $PROBLEMS_DIR/problem5.pdf
require_file $PROBLEMS_DIR/problem6.hpp
echo


# Grab the necessary files that were there.
echo "Gathering files for submission..."
gather_file $PROBLEMS_DIR/problem1.pdf
gather_file $PROBLEMS_DIR/problem2.pdf
gather_file $PROBLEMS_DIR/problem3.hpp
gather_file $PROBLEMS_DIR/problem3.cpp
gather_file $PROBLEMS_DIR/problem4.pdf
gather_file $PROBLEMS_DIR/problem5.pdf
gather_file $PROBLEMS_DIR/problem6.hpp
cd $TEMP_DIR
tar cvfz $TARGZ_PATH *

echo
echo "Take note of the list of files above.  Those are the only ones"
echo "that have been gathered."

